### PR TITLE
fix: name may be undefined

### PR DESCRIPTION
**Pull request by nanokind**
if `modulePath` is "node_modules", `segments[index + 1]` is undefined

### CODE REVIEW

**Comment by i-like-robots** [comment]
Thank you for submitting this change, would you mind also adding a test (to [the spec here](https://github.com/i-like-robots/get-package-name/blob/main/tests/spec.js)) or update the PR description with an example module path so I can update the tests?

**Comment by nanokind** [comment]
> Thank you for submitting this change, would you mind also adding a test (to [the spec here](https://github.com/i-like-robots/get-package-name/blob/main/tests/spec.js?rgh-link-date=2021-09-27T21%3A08%3A35Z)) or update the PR description with an example module path so I can update the tests?

Sure, tests were added and I also added some other small changes when I writing tests 😀

- use `prettier --check` instead of `prettier --list-different` for a human-friendly summary message to stdout
- add `*.js` to prettier file patterns( index.js is not handled by prettier before )
- add `format` to npm scripts
- change `jsxBracketSameLine` to `bracketSameLine` in `.prettierrc.json` as [`jsxBracketSameLine` is deprecated](https://prettier.io/blog/2021/09/09/2.4.0.html#replace-jsxbracketsameline-option-with-bracketsameline-option-11006httpsgithubcomprettierprettierpull11006-by-kurtztechhttpsgithubcomkurtztech)

**Comment by i-like-robots** [comment]
Thank you @fengzilong - I'll publish this shortly

**Comment by i-like-robots** [comment]
I have now published your changes as v2.2.0. Please note I've refactored it slightly to ensure that `undefined` is always returned when the package name cannot be found. Thanks again.

**Pull request merged**
